### ISSUE TITLE
Shouldn't kinetic releases use the kinetic-devel branch?

### ISSUE THREAD

**Issue by dirk-thomas** [RobotnikAutomation/rbcar_common-release#1]
https://github.com/RobotnikAutomation/rbcar_common-release/blob/65d57a0232a2f7f2ef6b29d84cb2de23593d626d/tracks.yaml#L39

The current default branch is indigo-devel...

**Comment by dirk-thomas** [comment]
Same for `rbcar_sim`.

**Comment by carlos3dx** [comment]
Fixed :3
